# ================================
# Android Appium Configuration
# Sesuai setup Ikram:
# adb devices -> emulator-5554 device
# adb shell getprop ro.build.version.release -> 15
# ================================
platformName=Android
automationName=UiAutomator2
deviceName=emulator-5554
platformVersion=15

# Skill2Lead AndroidDemoApp
appPackage=com.skill2lead.appiumdemo
appActivity=com.skill2lead.appiumdemo.MainActivity
appPath=apps/Android_Appium_Demo.apk

# Appium Server
appiumServerUrl=http://127.0.0.1:4723

# Wait Configuration
implicitWait=10
explicitWait=15

# Report Configuration
reportPath=test-output/ExtentReport.html
screenshotPath=test-output/screenshots/

# Optional execution settings
noReset=false
fullReset=false
